#!/usr/bin/env python3
"""Scan gems/*/meta.yaml -> registry.md. Validates each `uses:` module path exists."""
import sys, pathlib
try:
    import yaml
except ImportError:
    sys.exit("Install pyyaml: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parents[1]
rows, errors = [], []

for meta in sorted(ROOT.glob("gems/*/meta.yaml")):
    data = yaml.safe_load(meta.read_text())
    mods = data.get("uses", []) or []
    for ref in mods:
        if not (ROOT / ref).exists():
            errors.append(f"{meta.parent.name}: missing module '{ref}'")
    url = data.get("gem_url")
    gem = f"[Open]({url})" if url else "— not created"
    mod_names = ", ".join(pathlib.Path(m).stem for m in mods) or "—"
    rows.append((
        data.get("name", meta.parent.name),
        gem,
        data.get("version", "?"),
        data.get("owner", "?"),
        data.get("status", "?"),
        mod_names,
    ))

lines = ["# Gem Registry\n",
         "_Auto-generated by scripts/build_registry.py — do not edit by hand._\n",
         "| Gem | Link | Version | Owner | Status | Modules used |",
         "|---|---|---|---|---|---|"]
for r in rows:
    lines.append("| " + " | ".join(str(x) for x in r) + " |")
(ROOT / "registry.md").write_text("\n".join(lines) + "\n")

print(f"Wrote registry.md with {len(rows)} gem(s).")
if errors:
    print("\nVALIDATION ERRORS:")
    for e in errors:
        print("  -", e)
    sys.exit(1)
