#!/usr/bin/env python3
"""Scan skills/*/meta.yaml and (re)write registry.md. Validates `uses:` paths exist."""
import sys, pathlib
try:
    import yaml
except ImportError:
    sys.exit("Install pyyaml: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parents[1]
rows, errors = [], []

for meta in sorted(ROOT.glob("skills/*/meta.yaml")):
    data = yaml.safe_load(meta.read_text())
    for ref in data.get("uses", []) or []:
        if not (ROOT / ref).exists():
            errors.append(f"{meta.parent.name}: missing shared block '{ref}'")
    url = data.get("gem_url")
    gem = f"[Open]({url})" if url else "— not deployed"
    rows.append((
        data.get("name", meta.parent.name),
        data.get("version", "?"),
        data.get("owner", "?"),
        data.get("status", "?"),
        gem,
    ))

lines = ["# Skill Registry\n",
         "_Auto-generated by scripts/build_registry.py — do not edit by hand._\n",
         "| Skill | Version | Owner | Status | Gem |",
         "|---|---|---|---|---|"]
for r in rows:
    lines.append("| " + " | ".join(str(x) for x in r) + " |")
(ROOT / "registry.md").write_text("\n".join(lines) + "\n")

print(f"Wrote registry.md with {len(rows)} skill(s).")
if errors:
    print("\nVALIDATION ERRORS:")
    for e in errors:
        print("  -", e)
    sys.exit(1)
